### ISSUE TITLE
How to debug application not starting

### ISSUE THREAD

**Issue by khaledhosny** [justvanrossum/fontgoggles#116]
I’m building from source (to test some change, but trying a fresh build), and pytest passes but the app bundle won’t start (clicking on it, or running from terminal) and I get no messages either on the terminal or the log console and I can’t figure anyway to see why it doesn’t run.

This is probably a novice question, but app bundles are a complete mystry to me. Alternatively, I’d appreciate of there is anyway to try FontGoggles without the app bundle.

**Comment by typemytype** [comment]
You can execute `FontGoggles.app/Contents/MacOs/FontGoggles` after a build in terminal to get tracebacks.

**Comment by typemytype** [comment]
and if you like to trace everything add `FontGoggles.app/Contents/MacOs/FontGoggles -NSTraceEvents YES`

**Comment by khaledhosny** [comment]
Thanks, all I get now on the terminal is this:
```
2020-09-07 19:19:18.122 FontGoggles[4460:31177] The Info.plist file must have a PyRuntimeLocations array containing string values for preferred Python runtime locations.  These strings should be "otool -L" style mach ids; "@executable_stub" and "~" prefixes will be translated accordingly.
```

The application does not exit but no Window is shown either.

**Comment by justvanrossum** [comment]
Yeah, I usually launch with `./App/dist/FontGoggles.app/Contents/MacOS/FontGoggles`. I assume you know about py2app's `-A` flag?

**Comment by justvanrossum** [comment]
Hm, never seen that error. Best to build with the venv active (`python App/setup.py py2app -A`), then launch as above. Does that give the same error?

**Comment by khaledhosny** [comment]
I also I see this now in the log console:
```
Sandbox: FontGoggles(4460) System Policy: deny(1) file-read-data /Users/khaled/Library/Autosave Information
Violation:       System Policy: deny(1) file-read-data /Users/khaled/Library/Autosave Information 
Process:         FontGoggles [4460]
```

No difference with `python App/setup.py py2app -A`.

`./App/dist/FontGoggles.app/Contents/MacOS/FontGoggles` immediately exits and prints nothing at all. I can’t get to do anything unless I `cd App/dist/` and run `./FontGoggles.app/Contents/MacOS/FontGoggles`, which gives the errors above.

**Comment by justvanrossum** [comment]
It's really odd that you have to cd into `App/dist/`. If I google that error I don't find much that I understand.

Which version of macOS are running?

Which build of Python are you using? I haven't tested with anything but the 64-bit 3.7 installer from python.org.

**Comment by khaledhosny** [comment]
OK, turns out to be related to me using Python 3.8. I still don’t know what is the issue, but I now installed Python 3.7 and used it successfully to build and run the app.

**Comment by justvanrossum** [comment]
Ok, thanks. I'll try to see what's up with 3.8.

**Comment by justvanrossum** [comment]
Confirmed that things do not work with 3.8 :( I don't even get your error, though.

**Comment by justvanrossum** [comment]
Oh, it seems to work with 3.8 if py2app is upgraded to the current version. FG pins it to 0.19, I need to check why, and whether it is still necessary.

**Comment by justvanrossum** [comment]
Yeah, it relates to https://github.com/ronaldoussoren/py2app/issues/281
