### ISSUE TITLE
Unable to open Yu Gothic

### ISSUE THREAD

**Issue by batgh** [justvanrossum/fontgoggles#156]
When opening Windows' Yu Gothic (YuGothM.ttc, not Mac's), it gets circled cursor. FontForge can open the font. Is this known issue?

![image](https://user-images.githubusercontent.com/2231326/114156373-78a4b300-995d-11eb-9468-c3188ab844e8.png)

**Comment by justvanrossum** [comment]
No, not a known issue, thanks for reporting! I'll have a look.

**Comment by justvanrossum** [comment]
Fixed in release 1.1.20.
