### ISSUE TITLE
Display COLRv1 using BlackRenderer?

### ISSUE THREAD

**Issue by drott** [justvanrossum/fontgoggles#162]
It'd be cool to be able to use [BlackRenderer](https://github.com/BlackFoundryCom/black-renderer) output in the preview to be able to look at COLRv1 fonts.

**Comment by drott** [comment]
CC @anthrotype @rsheeter

**Comment by justvanrossum** [comment]
Yup, that's the plan! The CoreGraphics backend was made with this in mind.

**Comment by justvanrossum** [comment]
This is functionally done.

I need to refactor the UI colors vs COLR palettes logic, as it currently performs poorly on large palettes, due to excessive and eager conversion between rgba tuples and NSColor instances.

**Comment by justvanrossum** [comment]
I just released FG 1.2.0, which includes the COLRv1 support. Please give it a go!
