### ISSUE TITLE
Code point column is too narrow

### ISSUE THREAD

**Issue by dscorbett** [justvanrossum/fontgoggles#165]
The “unicode” column of the left panel cannot be resized and is too narrow for some non-BMP code points.
<img width="305" alt="Example of “U+2BC00” truncated to “U+2BC0”" src="https://user-images.githubusercontent.com/1124347/118363681-8acccf00-b563-11eb-9e28-f868812e771c.png">

**Comment by justvanrossum** [comment]
Ah, thank you. It's the same in the Unicode Picker. Will fix both.

**Comment by justvanrossum** [comment]
Fixed in release 1.1.20.
