### ISSUE TITLE
support variable COLRv1 table

### ISSUE THREAD

**Issue by anthrotype** [justvanrossum/fontgoggles#176]
FreeType/Chrome don't support variable COLRv1 (i.e. with a VarStore containing deltas for gradients, etc.) yet.
It would be nice if FontGoggles added support for this.

Yes, we need [test fonts](https://github.com/googlefonts/color-fonts/issues/60).

Also, nanoemoji can't build variable COLRv1 at the moment (only color font that are variable in their glyph outlines): https://github.com/googlefonts/nanoemoji/issues/294

fontTools has only recently added support for 32-bit VarStore, required to variate some of the COLRv1 fields; but fontTools.varLib still hasn't been updated to create a variable COLRv1 table from a set of masters: https://github.com/fonttools/fonttools/issues/2328:

**Comment by justvanrossum** [comment]
> It would be nice if FontGoggles added support for this.

It already does: blackrenderer fully supports variable COLRv1.

**Comment by anthrotype** [comment]
ah! amazing, thanks Just! Have you created a test font?

**Comment by justvanrossum** [comment]
![image](https://user-images.githubusercontent.com/4246121/120312712-5da94c00-c2d9-11eb-9a02-275da01f124e.png)

ColorTestFont-VF.ttf.zip

**Comment by justvanrossum** [comment]
This is rather shitty, therefore not yet part of any test suite... Will work on a better one.

**Comment by justvanrossum** [comment]
[ColorTestFont-VF.ttf.zip](https://github.com/justvanrossum/fontgoggles/files/6575729/ColorTestFont-VF.ttf.zip)

**Comment by justvanrossum** [comment]
Also: this test font uses PaintScale and PaintLocation from https://github.com/fonttools/fonttools/pull/2302

**Comment by justvanrossum** [comment]
Sooo with the "current" COLRv1 developments this regressed: I need to do more work on blackrenderer. Upstream issue: https://github.com/BlackFoundryCom/black-renderer/issues/53

**Comment by justvanrossum** [comment]
Ah yes, thanks!
