### ISSUE TITLE
UFOs not showing up

### ISSUE THREAD

**Issue by colinmford** [justvanrossum/fontgoggles#185]
Hi @justvanrossum, 

I've been noticing that the most recent version of FontGoggles (v1.3.1) doesn't show UFOs when you drag them in. Tested in macOS 10.15 and 11.

**Steps to Produce:**

1. Open FontGoggles, drag in a UFO or UFOZ (like the Mutator Sans UFOs in the test/data folder)
2. FontGoggles will spin a little bit, but nothing will show up in the view, and features do not get listed:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/671409/127032372-f7c34637-9e88-4f41-a808-373901459bba.png">

All FontGoggles tests seem to pass, and FontGoggles doesn't give any traceback in the window, so this is strange. Even more strange, dragging in a DesignSpace file _will_ work.

1.2, 1.3, and 1.3.1 releases all exhibit the same error, the last release that works for me is 1.1.21. So, this seems to be linked to the COLRv1 support?

Let me know if you need any more info!

**Comment by justvanrossum** [comment]
Oh dear, that's an embarrising bug! I'm on it. Thanks for reporting.

**Comment by justvanrossum** [comment]
Should be fixed in 1.3.2 https://github.com/justvanrossum/fontgoggles/releases/tag/v1.3.2

**Comment by colinmford** [comment]
@justvanrossum Indeed, it does work again! Thanks for the quick fix!
