### ISSUE TITLE
COLRv1 fonts do not work

### ISSUE THREAD

**Issue by khaledhosny** [justvanrossum/fontgoggles#197]
I don’t know what I’m missing, but I can’t get any COLRv1 font from https://github.com/googlefonts/color-fonts to show anything in FontGoggles, not even glyph name in the Glyph List panel. Same fonts work with Chrome Canary.

**Comment by khaledhosny** [comment]
I see. Thanks.

**Comment by justvanrossum** [comment]
This should be mostly fixed, except for variability: all the `PaintVar*` paints don't currently work.

Would you able to test this from the sources? Ideally I would like a confirmation from you that this works before I push a release.

**Comment by khaledhosny** [comment]
I manged to get it build and the font I}m working on displays fine now, thanks!

**Comment by justvanrossum** [comment]
Thanks! Will make a release soon.
