### ISSUE TITLE
The Icon Looks Broken

### ISSUE THREAD

**Issue by yevgenyloginov** [justvanrossum/fontgoggles#202]
As it appears on the picture, the icon in my current version of FontGoggles looks a bit broken. Resizing the window or maximizing it doesn't change anything. 

The button works and everything else is fine.

![FontGoggles icons comparison](https://user-images.githubusercontent.com/90870625/139252790-342fd7a3-15fd-47dc-8afe-e6208c4a630d.png)

**Comment by yevgenyloginov** [comment]
![Снимок экрана 2021-11-08 в 16 43 41](https://user-images.githubusercontent.com/90870625/140752781-df09e308-40b7-493f-a3fb-42c83c8e96d0.png)

Thanks for the fix!

**Comment by justvanrossum** [comment]
Hm, that's a very different icon all of a sudden :(

**Comment by yevgenyloginov** [comment]
I thought it looks like that by design now. It is the same in different resolutions (I don't know what else to try to test it).

**Comment by typemytype** [comment]
that is Monterey.. NSImageNameActionTemplate has a different drawing

**Comment by justvanrossum** [comment]
@typemytype It's a vanilla `ActionButton`. The last FontGoggles also updated the vanilla dependency, could the appearance have changed with that?

**Comment by typemytype** [comment]
see this gist to visualise all named images: https://gist.github.com/typemytype/78a26b77eb1c23367cc68f1792153c2f

**Comment by typemytype** [comment]
and the first item of an ActionButton is `NSImageNameActionTemplate `
https://github.com/robotools/vanilla/blob/f62d92951048adc6d6f65e00e81b3c788d202205/Lib/vanilla/vanillaPopUpButton.py#L221
