### ISSUE TITLE
A font with COLRv1 table crashes FontGoggles

### ISSUE THREAD

**Issue by khaledhosny** [justvanrossum/fontgoggles#213]
Opening the attached font in FontGoggles and typing `ح` will cause a crash. The font is faulty since one of its paints is referring to the glyph itself, but at least the app shouldn’t crash.

[crash.subset.zip](https://github.com/justvanrossum/fontgoggles/files/7610928/crash.subset.zip)

**Comment by justvanrossum** [comment]
Thanks for reporting. Indeed it shouldn't crash. Fill fix in blackrenderer.

**Comment by justvanrossum** [comment]
Should be fixed in v1.4.1.

**Comment by khaledhosny** [comment]
Thanks!
