### ISSUE TITLE
Need to upgrade to Python 3.10

### ISSUE THREAD

**Issue by justvanrossum** [justvanrossum/fontgoggles#222]
Eg. Numpy is no longer supported on 3.7: https://github.com/justvanrossum/fontgoggles/runs/4693724251

**Comment by typemytype** [comment]
oh

**Comment by justvanrossum** [comment]
https://github.com/justvanrossum/fontgoggles/pull/259

**Comment by justvanrossum** [comment]
Good news: numpy 1.24.0 does work on macOS 10.10 with the wheels from PyPI, it least with Python 3.9.
