### ISSUE TITLE
No automatic mark feature when viewing designspace files

### ISSUE THREAD

**Issue by BoldMonday** [justvanrossum/fontgoggles#226]
Due to its support for designspace files, FontGoggles is a great tool for testing variable fonts while they’re still in development.

If the source UFOs contain kerning then FG automatically compiles a `kern` feature (which is great).
But FG does not automatically compile a `mark` feature when the source UFOs contain anchors.

Is there a particular reason for this difference?

**Comment by justvanrossum** [comment]
It should do that, so perhaps this indicates a bug.

- Does the mark feature get built if you build the VF with fontmake?
- Does it also not work when previewing a single UFO source?

**Comment by BoldMonday** [comment]
>     * Does the mark feature get built if you build the VF with fontmake?

Fontmake does build a `mark` feature in this case. (That’s how I discovered this issue.)

>     * Does it also not work when previewing a single UFO source?

There is also no `mark` feature when previewing a single UFO.

**Comment by BoldMonday** [comment]
Let me know if you want to look at the files in question.

**Comment by justvanrossum** [comment]
Yes please, because it does work with my test font.

**Comment by BoldMonday** [comment]
Mail sent.

**Comment by justvanrossum** [comment]
The cause is that your sources are UFO 2. It does work when they're converted to UFO 3.

I'll have a look what it would take to make FG support UFO 2 here.

**Comment by BoldMonday** [comment]
Yeah, sorry for being old skool...

No problem if it’s too much hassle to fix for UFO2.

**Comment by justvanrossum** [comment]
Fixed in 1.4.3: https://github.com/justvanrossum/fontgoggles/releases/tag/v1.4.3
