### ISSUE TITLE
TODO UnicodePicker

### ISSUE THREAD

**Issue by justvanrossum** [justvanrossum/fontgoggles#23]
- [x] Consider using a Popover panel that attaches to the text entry
- [x] implement automatic "show more": right now long result lists are truncated at 500 items

**Comment by colinmford** [comment]
I like this little guy, but what are the advantages of having this versus the default Mac OS Character Viewer?

One thing that might be useful (at least for type designers...) is to allow users to search by [GNFUL](https://github.com/LettError/glyphNameFormatter) as well?

**Comment by justvanrossum** [comment]
Not all that much, but at least these:

- you can use multiple search terms to narrow your search, for example "ara lett" will give you Arabic letters
- gives you a nice list of results, allowing multiple selection
- you can enter unicode literals, like `12BA`, `U+1234`, `0x1234`, or glyphname-like Unicode literals like `u1234` and `uni1234`

The GNFUL names are often based on the unicode name, so I bet you can find the right unicode by separating the elements from the GNFUL name by spaces.

It seems the system picker has more keywords than just the unicode name, at least for emoji. Searching for "pile" there also gives the "books" emoji, even though it doesn't have the word "pile" in the name.

**Comment by justvanrossum** [comment]
The todo items are actually done:

- Popover: I considered, rejected
- Show more: not completely automatic, but clicking ...more... will add 500 more search results.

Therefore I'm closing this.
