### ISSUE TITLE
Feature request: paragraph text view with line-breaking

### ISSUE THREAD

**Issue by eliheuer** [justvanrossum/fontgoggles#289]
It might be helpful to have a view for comparing two or more fonts in Font Goggles in a paragraph text view with line-breaking.

@weiweihuanghuang suggested this here: https://typo.social/web/@w__h_/109346482205707259

Font Drop is an example of what this looks like in a web UI: https://fontdrop.info/#/compare

If there is a way to do this easily in Font Goggles I haven't found it, please close this issue if it is already possible.

**Comment by justvanrossum** [comment]
FontGoggles is currently fundamentally a single line viewer, so this is not possible.

**Comment by justvanrossum** [comment]
Perhaps an idea for FontGoggles 2.0, if that will ever happen. For now I will close this as "not planned".
