### ISSUE TITLE
Ability to copy the output glyph sequence

### ISSUE THREAD

**Issue by typoman** [justvanrossum/fontgoggles#29]
There is this vertical list of output glyph sequence next to the input character sequence. I was wondering it would be handy if I could copy a srting of space seperated glyph names from this glyph sequence. Maybe selecting the list and hitting CMD+C would be enough?

**Comment by justvanrossum** [comment]
Look @lianghai, there's some synchronicity...

**Comment by justvanrossum** [comment]
This is now implemented, release will follow later today.

It's a little different and more general than you requested: it will copy the selection as a tab-separated bit of text. However, I also added the ability to select table columns, so if you click the glyph name column, and then do copy, you get only the glyph names for all rows. Not space-separated, but as lines.

**Comment by typoman** [comment]
Thank you very much Just, all that matters is to get the glyph sequnce in a text. Cheers!
