### ISSUE TITLE
Support DS5 discrete axes

### ISSUE THREAD

**Issue by LettError** [justvanrossum/fontgoggles#291]
DS5 discrete axes need a different treatment - not have a slider. Maybe use [splitInterpolable](https://fonttools.readthedocs.io/en/latest/designspaceLib/python.html#fontTools.designspaceLib.split.splitInterpolable) to split a designspace into separate VFs and display each on a separate line.

**Comment by justvanrossum** [comment]
That indeed sounds like a reasonable solution, thanks.
