### ISSUE TITLE
Feature Request: Character / glyph table

### ISSUE THREAD

**Issue by behdad** [justvanrossum/fontgoggles#301]
Maybe it's already there and I don't find it, but a character and glyph table viewer would be nice. I want to browse a font's coverage and inspect it visually in a glance.

**Comment by justvanrossum** [comment]
Duplicate of #56 and #59.

It would be a pretty big new feature, and is currently out of scope, given the funding status of FontGoggles.

This is the sort of thing that https://wakamaifondue.com/ should be good at (at least for binary fonts).

**Comment by behdad** [comment]
Thanks. I might take a stab at it at some point.

**Comment by behdad** [comment]
> https://wakamaifondue.com/

The reason I like to do in FontGoggles is because then I can render with latest (experimental) features in HarfBuzz without building Chrome with those.

**Comment by justvanrossum** [comment]
Makes sense. A fonttools + uharfbuzz script that would output an SVG with the full glyph set could perhaps be a short term solution.

**Comment by cesss** [comment]
Count my vote as well. I was looking for a Mac application which would let me see every glyph that is available in fonts that I'm inspecting, and thought that FontGoggles would do it.
