### ISSUE TITLE
Apply kerning between Hiragana and Katakana

### ISSUE THREAD

**Issue by Hoolean** [justvanrossum/fontgoggles#310]
## Issue

Kerning is not shown between Hiragana and Katakana characters

## Example

"すペ" in [Noto Sans JP](https://github.com/justvanrossum/fontgoggles/files/10479387/Noto_Sans_JP.zip) (sourced from Google Fonts), which has kerning that is not displayed

## Further Context

Hiragana and Katakana characters belong to [separate Unicode scripts](https://unicode.org/standard/supported.html), "Hira" and "Kana", but it is not uncommon for characters from both scripts to occur in the same run of text. In particular, the OpenType specification for font files classifies both Hiragana and Katakana [under the same script](https://learn.microsoft.com/en-us/typography/opentype/spec/scripttags), "kana", such that the same script-specific positioning and substitution features apply to both.

Chrome displays kerning between the two scripts, and Firefox [will begin doing so](https://bugzilla.mozilla.org/show_bug.cgi?id=1811471) in an upcoming release.

## Workaround

Disable BiDi and Segmentation

## Ideal Fix

Poke Hiragana and Katakana into the same segment, so that they can interact with each other

## Other Notes

The vertical kerning of "しチ" in the same test fonts is not affected, possibly because segmentation is not enabled for Top-to-Bottom

**Comment by justvanrossum** [comment]
Thanks for the detailed report. Perhaps the segmentation could be done based on the opentype version of the script tag.

(Indeed, segmentation is not implemented for vertical layout, see also #52)

**Comment by justvanrossum** [comment]
#311 seems to fix this:
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/4246121/214047173-8b3f3410-c1d8-4f2e-b6aa-1c1c1f93dc5f.png">
