### ISSUE TITLE
Feature Request: Platform independence.

### ISSUE THREAD

**Issue by 100amps** [justvanrossum/fontgoggles#318]
This tool would be very useful, however I do not use a Mac.

**Comment by kenmcd** [comment]
Support PC (WIN/LINUX) #41 
I think the biggest block is some requirements are Mac-only (e.g. cocoa).
So the interface would have to be re-written in something more cross-platform like Qt, or...
Probably not going to happen unless GF funds it.
Since I use windows, I too would like to see this.
