### ISSUE TITLE
Question: FG and hb-shape give different results

### ISSUE THREAD

**Issue by pgundlach** [justvanrossum/fontgoggles#351]
This is related to a proprietary font and a vague question, I hope it is still okay to open it here.

The font `MinionPro-Regular.otf` shows for the word `fish` and no features turned on or off the following output:

```
f_i	532	0	0	0	234	
s	363	0	0	2	84	
h	534	0	0	3	73	
```
which is what I expect. (Same result when I activate the `liga` feature).

Now with harfbuzz (`hb-shape`) I get the following:

```
$ hb-shape MinionPro-Regular.otf fish
[f=0+306|i=1+265|s=2+363|h=3+534]
```

also with `+liga`:

```
hb-shape --features="+liga"  MinionPro-Regular.otf fish    
[f=0+306|i=1+265|s=2+363|h=3+534]
```

```
hb-shape --version                                     
hb-shape (HarfBuzz) 7.1.0
Available shapers: graphite2,ot,coretext,fallback
```

Question: is fontgoggles using special parameters when invoking the shaper? How can I reproduce the result from fontgoggles? 

(FG Version 1.7.4 (1.7.4))

**Comment by justvanrossum** [comment]
I'm getting `[f_i=0+532|s=2+363|h=3+534]` from `hb-shape`, although my version isn't quite up to date. FontGoggles uses uharfbuzz, but isn't doing anything special, really.

**Comment by pgundlach** [comment]
Thank you very much. I close this as it is now my job to find out why hb-shape is doing what it does.
