### ISSUE TITLE
RTL: glyph column reversed?

### ISSUE THREAD

**Issue by frankrolf** [justvanrossum/fontgoggles#366]
I am using FontGoggles to test some RTL behavior, and I am observing the following:
With the string `ههي`, I see the `char` and `unicode` columns follow logical order – heh `U+0647`, heh `U+0647` , and yeh `U+064A`. However, the `glyph` column seems to go from bottom to top – first the final yeh `uni064A.f`, then the medial heh `uni0647.m`, and then the initial heh `uni0647.i`.

In other words:

| char | unicode | glyph (observed) | glyph (expected) |
| --- | --- | --- | --- |
 | `ه` | U+0647 | uni064A.f | uni0647.i 
 | `ه` | U+0647 | uni0647.m | uni0647.m 
 | `ي` | U+064A | uni0647.i | uni064A.f 

Is this behavior expected?

<img width="1616" alt="Screenshot 2023-10-13 at 00 33 54" src="https://github.com/justvanrossum/fontgoggles/assets/2049645/de7b0b91-e0c0-451e-8d1f-04dfef97bb80">

The font in question is [Myriad Arabic](https://fonts.adobe.com/fonts/myriad-arabic), I am running FontGoggles Version 1.7.4 on macOS 13.5.2.

**Comment by frankrolf** [comment]
As selecting individual glyphs reveals, the problem seems to be purely display-related (note the split row highlighting on the left side):
<img width="1616" alt="Screenshot 2023-10-13 at 00 59 00" src="https://github.com/justvanrossum/fontgoggles/assets/2049645/f86b41c6-4421-4b54-92a3-24e501fa71cb">

**Comment by justvanrossum** [comment]
This is by design: the glyphs list shows the rendering order, which goes from left to right, regardless of the writing direction of the input text.

For extra entertainment try a bidirectional string, such as arabic with a bit of latin embedded, then arrow-key your way through the character list or the glyph list.

**Comment by frankrolf** [comment]
Okay, understandable. In a longer string it also becomes clear that the columns are independently scrollable, which is not obvious for a shorter example.

Thanks!

**Comment by justvanrossum** [comment]
Yeah, maybe there should be a bigger gap between the columns. I see how this can be confusing.
