### ISSUE TITLE
[request] option to show named instances for var fonts

### ISSUE THREAD

**Issue by cjdunn** [justvanrossum/fontgoggles#38]
I love this tool so far, thank you for making this! 

Currently it's handy to compare multiple styles, which I can do if I drag in generated static fonts for each style. As a user I'd like the option to see all named instances from a variable font (VF.ttf or .designspace) so I can compare characters or features across styles, particularly handy with things like feature variations.

Thanks for your consideration 🙏

**Comment by justvanrossum** [comment]
Duplicate of #25 :)

**Comment by cjdunn** [comment]
Oops, somehow missed that one, thanks!
