### ISSUE TITLE
[request] Hide font labels; column display (w/ sidebearing?)

### ISSUE THREAD

**Issue by tiroj** [justvanrossum/fontgoggles#39]
Nice tool!

I'm interested in the possibility of using FontGoggles for visual review of glyph design and spacing consistency across a family. For that, I find it helpful to have the glyphs directly proximate to each other, so wonder if you can add a View option to hide font labels, allowing the lines of preview text to be moved closer together and without visual noise from the labels.

For the same purpose, I like to be able to look at glyphs in a grid, so they're aligned veritcally and horizontally, so wonder if a columns view could be implemented? In column view, it would also be nice to have an option to display sidebearings, to be enable visual checking of spacing consistency.

**Comment by justvanrossum** [comment]
I'll add an option to hide the labels, thanks.

In your second question I don't really recognize FontGoggles' core business, which is text and variations behavior. It sounds like something a font editor should offer.

**Comment by justvanrossum** [comment]
Hide font labels has been implemented, and will be in the next release.
