### ISSUE TITLE
Selecting alternates in features with alternate substitution lookups

### ISSUE THREAD

**Issue by khaledhosny** [justvanrossum/fontgoggles#42]
One can enable/disable features, but if there are alternate substitution lookups then there is a need to list all alternates (1, 2, 2, etc.) and be able to select them.

In this font, `salt` feature uses alternate substitutions: [AbdAlQadir.otf.zip](https://github.com/justvanrossum/fontgoggles/files/4271510/AbdAlQadir.otf.zip)

**Comment by justvanrossum** [comment]
While I see this as a useful feature, it is a bit of a slippery slope, UI-wise, as it would make it go into the direction of rich text formatting. Your suggestion at #43 takes this indeed a step further.

But before I break my head and think of what the user interface for this could possibly be like: I don't think uharfbuzz exposes this at the moment. Or am I missing something?

**Comment by khaledhosny** [comment]
In uharfbuzz that would be the `value` of the feature (in other types of lookups non-zero value means enable, here it selects the alternate, 1 for 1st, 2 for 2nd etc.)

**Comment by justvanrossum** [comment]
I mean the range thing, as in:

`      "aalt[3:5]=2" 2         3         5         # Turn 2nd alternate on for range`

**Comment by khaledhosny** [comment]
I’m OK if this and #43 are out of scope, it just happens that the fonts I do right now are full of character-level alternates.

**Comment by khaledhosny** [comment]
The range would be for #43 not this one, and apparently it isn’t supported.

**Comment by justvanrossum** [comment]
But wouldn't you want to choose an alternate on a per-character basis?

Btw. I didn't know about the extended meaning of the feature value: thanks, that's very useful.

**Comment by justvanrossum** [comment]
But if this feature is already useful with one value for the entire string, then I see a UI possibility: perhaps control-click on the feature tag box that brings up a menu with alt indices.

**Comment by khaledhosny** [comment]
> But wouldn't you want to choose an alternate on a per-character basis?

Usually, but that wouldn’t be a requirement (I might want to test, e.g, a `ssty` feature in a math font, and so applying it to all charters would be fine or even what I really want).

**Comment by justvanrossum** [comment]
I have implemented this with a contextual menu for GSUB feature tags. It allows selection of an alternate number regardless of whether the feature actually uses alternates, as (u)harfbuzz doesn't expose an API to find this out quickly, and I don't want to parse GSUB with fontTools just to get this info.

TODO: document this on the website. Will do that when I'm closer to release (which should be soon anyway).

**Comment by justvanrossum** [comment]
FG v1.1 just landed containing this feature, and I wrote a note about it on the website.

**Comment by khaledhosny** [comment]
Thanks!
