### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by ToSupply** [justvanrossum/fontgoggles#429]
Hi,
Great tool, congrats!
Question: is there a way to create collections (and sub-collections) of font files in FontGoggles?
If not, is it planned or not at all?
Best Regards

**Comment by justvanrossum** [comment]
What do you mean with “collection” specifically?

**Comment by ToSupply** [comment]
I mean being able to classify fonts that you want to view in collections and sub-collections (a bit like a font manager).
It could be a left panel in which you could create folders, subfolders and drag fonts in them.
When you re-open, you find them still here.

**Comment by justvanrossum** [comment]
You can save the state of a window as a file for later reuse (command-S). FontGoggles isn't a font manager, and has no aspirations to develop into that direction.

**Comment by ToSupply** [comment]
Hi,
Thanks for your message.
I know, the intention behind my question is not at all to replicate a font manager.
Only the classification or viewing / browsing of files would be similar.

To explain a little more, the intended use is educational (graphic design school).
The idea was to have the graphic design students be able to view, compare and analyse fonts (before choosing to install them via other means).
Since they have access to many fonts, the idea would be that they could view fonts as the they are classified in the source files library (tree structure of 3 levels) delivered to them (serif, sans-serif, display, etc.).

I totally understand if that direction makes no sense for fontgoogles, I was just assessing if the school could consider presenting it to the student as the main tool to use for that purpose.

**Comment by justvanrossum** [comment]
FontGoggles is primarily a tool for font developers. I'm afraid the kind of usage you propose is quite far removed from the original scope.

**Comment by ToSupply** [comment]
Okay, I understand.
Thanks for those precisions.
