### ISSUE TITLE
Non-standard variation axes

### ISSUE THREAD

**Issue by khaledhosny** [justvanrossum/fontgoggles#44]
I’m trying a font with a non-standard variation axis, and the variation tab is empty. Not sure if there is something missing in the font or non-standard axes are not supported.

[RanaKufi-Regular.otf.zip](https://github.com/justvanrossum/fontgoggles/files/4271520/RanaKufi-Regular.otf.zip)

**Comment by justvanrossum** [comment]
I don't see an `fvar` table in that font, nor any other var-related tables.

**Comment by khaledhosny** [comment]
Silly me, I tested the wrong font. Sorry for the noise.
