### ISSUE TITLE
is python3.7 still recommended for venv?

### ISSUE THREAD

**Issue by stenson** [justvanrossum/fontgoggles#440]
I was following the build instructions in the README and tried building with python3.7 first, but got this error: `ERROR: No matching distribution found for setuptools==70.2.0` when doing the pip install -r requirements.txt step.

python3.8 and python3.9 both fail with `ERROR: No matching distribution found for numpy==2.1.1`

That said, 3.10, 3.11, and 3.12 all work fine, so there's really no "issue" here as far as functionality, but would it be worthwhile to update the README to not recommend python3.7/3.8? (Unless I'm missing something of course, and python3.7 is still the preferred venv python).

**Comment by justvanrossum** [comment]
Oh no, that info is out of date. I currently build the release with 3.12. I should probably require 3.10 or up based on your findings.
