### ISSUE TITLE
one OTF doesn't refresh in FG when regenerating via fontmake

### ISSUE THREAD

**Issue by cjdunn** [justvanrossum/fontgoggles#48]
- I generate some OTFs with fontmake
- I load those OTFs into FG, everything shows up fine
- I regenerate those OTFs via fontmake
-  one of the OTFs doesn't refresh in FG
- if I close the .gggl file and open again in FG, that OTF shows up again, so it seems there's no problem with the OTF data 

This is the traceback:

```
Traceback (most recent call last):
  File "fontgoggles/mac/mainWindow.pyc", line 488, in _loadFont
  File "fontgoggles/project.pyc", line 139, in load
  File "fontgoggles/project.pyc", line 172, in loadFont
  File "fontgoggles/font/otfFont.pyc", line 54, in load
  File "fontTools/ttLib/ttFont.pyc", line 139, in __init__
  File "fontTools/ttLib/sfnt.pyc", line 75, in __init__
fontTools.ttLib.TTLibError: Not a TrueType or OpenType font (not enough data)

```

Doesn't happen every single time, maybe every 3rd time or so? But when it does happen, it's always the last instance listed in the .designspace that I used in fontmake. If I change the order of instances in the designspace so that a different instance is listed last, the new last instance will be the one that has the problem in FG. Hopefully that helps to track down the issue. 

Not urgent at all but thought it's worth reporting in case this affects others as well. I can email you a screen recording of this happening if it would be helpful. Thanks!

**Comment by justvanrossum** [comment]
I know how this happens but am not 100% sure how to address it yet.

Which OS are you running this on?

It is related to fonttools/fonttools#536: fonttools first creates an empty file, then does a lot of work, and then writes the full data. FG gets a file changed event on the creation of the empty file, and is subsequently too quick to respond to that (the error you see is typical for creating a TTFont from an empty file). Normally a _second_ file changed event follows once data has been written, and if FG catches that all is good.

The resolution of modification time info differs per OS, and can affect how FG responds to file changes. Hence my question.

**Comment by cjdunn** [comment]
I’m using OS 10.15 Catalina. 

This may be dumb, but I was thinking that if FG hits an error like this it could just try again one time only, after a delay of say 10 seconds or so. It doesn’t keep looking for missing files after that, just the one extra time for cases like this. Maybe not the most elegant solution, but do you think something like that would work? Thanks!

**Comment by justvanrossum** [comment]
This should be fixed in the latest release. Please reopen if you still see this happening.
