### ISSUE TITLE
Components not updating via designspace that uses support layers

### ISSUE THREAD

**Issue by cjdunn** [justvanrossum/fontgoggles#53]
My designspace uses supports layers with components. 

The components show up fine using the generated var font in FG, but if I use the designspace in FG the characters which contain nested components don't change when I move the sliders, only the non-componented glyphs change. Thanks!

**Comment by justvanrossum** [comment]
Interesting! I'll look into it.

**Comment by justvanrossum** [comment]
I found the problem, and am working on a solution.

**Comment by justvanrossum** [comment]
#54 fixed this.

**Comment by justvanrossum** [comment]
The problem you reported privately that the fix to this introduced should be gone in the latest release.
