### ISSUE TITLE
Character Overview

### ISSUE THREAD

**Issue by Colophon-Foundry** [justvanrossum/fontgoggles#56]
It would be great to be able to have a view where it shows all characters available within a font. For error checking instances and interpolation across multiple axes this can take a while when typing characters individually.

Having a grid view (similar to Glyphs/Robofont) would give a quick overview of all the characters.

**Comment by justvanrossum** [comment]
Thank you for your suggestion.

FontGoggles is not a discovery app, and it will not make a font editor redundant. Its main focus is text and variation behavior across multiple fonts.

Who knows in which direction FontGoggles will evolve in the long term, but right now I don't think this feature request is a good match for what the app aims to be.
