### ISSUE TITLE
Feature list is omitting features after listing some stylistic sets

### ISSUE THREAD

**Issue by kontur** [justvanrossum/fontgoggles#63]
Hey,

I've noticed with one font that some features seem to be missing and tested with a few different fonts (otf, ttf, variable font, more features, less features, only certain features). It seems something in the listing of stylistic sets is "breaking" and all features following alphabetically later are dropped from the features listing. This seems to happen during or after the listing of stylistic sets only, afaik, but oddly enough the first `ssXX` are listed still, but the rest of `ssXX` and all features after (like `zero`).

To have a reproducible case I am viewing [this font](https://github.com/google/fonts/blob/master/ofl/cormorant/Cormorant-Bold.ttf) with FontGoogles Version 1.1.4.

Stylistic sets as listed in Adobe InDesign CC 2020:
<img width="797" alt="Screenshot 2020-03-16 at 12 01 24" src="https://user-images.githubusercontent.com/1893577/76745465-9285bd80-677e-11ea-876e-9f03ecc95701.png">

Versus the feature listing in FG:
<img width="1117" alt="Screenshot 2020-03-16 at 12 01 36" src="https://user-images.githubusercontent.com/1893577/76745497-9d405280-677e-11ea-879e-5e795d85dfc6.png">

I am wondering if the culprit has something to do with the list of `ssXX` after the first not defined set, e.g. this font has `ss01`—`ss04` then has no `ss05` but has `ss06`—and seems to omit all after `ss04`. Equally another font I tested has `ss01` and `ss02` but has no `ss03` but does have `ss04` and omits everything after `ss02`. Or maybe this is incidental.

**Comment by justvanrossum** [comment]
Thanks, sounds like a bug. I'll look into it.

**Comment by justvanrossum** [comment]
It's a bug in `uharfbuzz`: https://github.com/harfbuzz/uharfbuzz/issues/31

**Comment by kontur** [comment]
Nifty find, and so quick 👍 
Yep, looks like all three fonts I've replicated it with seem to cut off exactly after 24 feature tags, it just incidentally happens to be mid-way of the stylistic sets each time.

**Comment by justvanrossum** [comment]
Fixed in version 1.1.6.

**Comment by kontur** [comment]
Can confirm this works correctly with all fonts I encountered the problem with. Big thanks for the quick fix 👍
