### ISSUE TITLE
OpenType language tag != BCP 47 tag

### ISSUE THREAD

**Issue by justvanrossum** [justvanrossum/fontgoggles#68]
We need to convert the OpenType language tag to a BCP 47 language tag before passing it to HarfBuzz.

How?

**Comment by justvanrossum** [comment]
I feel that uharfbuzz should have used

- `hb_ot_tag_to_language`
- `hb_ot_tag_to_script`

instead of 

- `hb_language_from_string`
- `hb_script_from_string`

**Comment by justvanrossum** [comment]
I already worked around it for script in https://github.com/justvanrossum/fontgoggles/commit/6418df504cbfe3f611a7654844c8276a2d930d1b
but for language it will be harder. Perhaps the uharfbuzz buffer should get `ot_script` and `ot_language` properties.

**Comment by khaledhosny** [comment]
You can use private language tags, `hbot` prefiz for language e.g. `x-hbotara` for `ARA`, and `hbsc` for script. Combind `x-hbotara-hbscarab` sets language to OpenType tag `ARA` and script to OpenType tag `arab`.

**Comment by khaledhosny** [comment]
cc @dscorbett

**Comment by justvanrossum** [comment]
> You can use private language tags [ ... ]

Ah, so that allows me to fix it without changing uharfbuzz.

(On the other hand, my uharfbuzz addition is useful in its own right I suppose.)

**Comment by justvanrossum** [comment]
Hmm, I'm not sure how I should apply that combined string in uharfbuzz, or how I should apply each separately. Language works, but I must be doing something wrong with script.

```python
            buf.language = f"x-hbot{language}hbsc{script}"
            print(language, buf.language)
            print(script, buf.script)
```

**Comment by justvanrossum** [comment]
`buf.script` gives the guessed script, so I'm not sure I'm doing this right.

**Comment by khaledhosny** [comment]
This is true. The script will remain unset, but when HarfBuzz is preparing for shaping it will check the language first and if it has a private script subtag it will be used instead of the set script.

But, something is not working indeed with setting script this way, it seems to take effect to late that the correct shaper is not used.
