### ISSUE TITLE
Allow to switch font feature in one click

### ISSUE THREAD

**Issue by guidoferreyra** [justvanrossum/fontgoggles#90]
I find that sometimes it can be useful to directly switch from on/off instead of cylcing trough gray/greeen/red. 
I imagine that this can be made in a unobstrusive way by using a modfifier key (cmd or alt?) when clicking the feature button.

**Comment by justvanrossum** [comment]
Makes sense, that's a good suggestion. Leaning towards "alt" for this.

**Comment by justvanrossum** [comment]
While playing with this I realized the simplest thing to do is for the alt key to reverse the cycling direction. alt-gray -> red, alt-green -> gray, alt-red -> green.

**Comment by justvanrossum** [comment]
Implemented in e34a86b43ab17d6f48a2c59b208113d790220141.

**Comment by justvanrossum** [comment]
Release 1.1.15 is out, containing this feature.

**Comment by guidoferreyra** [comment]
Wow that was fast!! Thanks a lot.
