### ISSUE TITLE
Auto update?

### ISSUE THREAD

**Issue by khaledhosny** [justvanrossum/fontgoggles#92]
I have seen in more than one occasion people using old versions and not aware about newer ones. No idea how hard is this, but t would be great if there was some sort of autoupdate functionality or at least a notification that a new version is available.

**Comment by khaledhosny** [comment]
Duplicate of #77 I guess.

**Comment by justvanrossum** [comment]
That would be nice indeed, but I have no experience with such mechanisms, and right now no capacity to work on it.

DrawBot has a feature where it will compare the version of latest download to the current version, and will show an alert with a manual download link if there's a new one out. And then people still complain: "it's so cumbersome to download an install a new version". As if it isn't free software. But I digress :)
