### ISSUE TITLE
FontGoggles alternative app for Windows 10

### ISSUE THREAD

**Issue by xmha97** [justvanrossum/fontgoggles#97]
Hello,
I looking for FontGoggles alternative app for Windows 10.
Please help me.

**Comment by justvanrossum** [comment]
I only know of a few on-line apps that have some overlapping functionality, but you probably already know those:

- https://www.axis-praxis.org/
- https://dinamodarkroom.com/gauntlet/

See also #41.

**Comment by xmha97** [comment]
OK, Thanks.
I closing this issue.
